add missing dependencies section
puppet requires a dependencies section:

 # puppet module list --tree --environment puppet4
 Error: No dependencies module metadata provided for backports